# Generated by Django 4.2 on 2023-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["title"],
                "verbose_name": "Заголовок",
                "verbose_name_plural": "Заголовки",
            },
        ),
        migrations.RemoveField(
            model_name="menu",
            name="link",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="name",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="order",
        ),
        migrations.AddField(
            model_name="menu",
            name="named_url",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="menu",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menu",
            name="url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
