# Generated by Django 4.2 on 2023-04-26 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "blog",
            "0002_alter_menu_options_remove_menu_link_remove_menu_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={
                "ordering": ["menu_name"],
                "verbose_name": "Заголовок",
                "verbose_name_plural": "Заголовки",
            },
        ),
        migrations.RenameField(
            model_name="menu",
            old_name="title",
            new_name="menu_name",
        ),
    ]
