# Generated by Django 4.2 on 2023-04-27 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_menuitem_delete_menu"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["name"],
                "verbose_name": "Название",
                "verbose_name_plural": "Названия",
            },
        ),
    ]
