# Generated by Django 4.2 on 2023-04-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_menuitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="url",
            field=models.CharField(
                blank=True, max_length=200, null=True, unique=True
            ),
        ),
    ]
